/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BigExercise;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Orange
 */
public class Diemsinhvien extends javax.swing.JPanel {

    /**
     * Creates new form Diemsinhvien
     */
    private String hoten,ngaysinh,gioitinh,quequan,gmail,khoa,lop,diemchu, sdt;
    
    public Diemsinhvien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_diemcc = new javax.swing.JTextField();
        txt_diemgk = new javax.swing.JTextField();
        bt_refresh = new javax.swing.JButton();
        txt_hocphan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_diemck = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ketqua2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txt_masv = new javax.swing.JTextField();
        bt_luudiem = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bt_suatt = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        cb_tinchi = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel10.setText("Điểm giữa kỳ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel11.setText("Điểm cuối kỳ");

        bt_refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/new-icon-16.png"))); // NOI18N
        bt_refresh.setText("Làm mới");
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Mã sinh viên");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/logo-1.png"))); // NOI18N

        tb_ketqua2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Học phần", "Số tín chỉ", "Điểm chuyên cần", "Điểm giữa kỳ", "Điểm cuối kỳ", "Thang điểm 10", "Thang điểm 4", "Điểm chữ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_ketqua2);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel8.setText("Học phần");

        bt_luudiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_luudiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/Save-icon.png"))); // NOI18N
        bt_luudiem.setText("Lưu điểm");
        bt_luudiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_luudiemActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setText("Điểm chuyên cần");

        bt_suatt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_suatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/Actions-document-edit-icon-16.png"))); // NOI18N
        bt_suatt.setText("Sửa điểm");
        bt_suatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suattActionPerformed(evt);
            }
        });

        bt_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        bt_xoa.setText("Xóa thông tin");
        bt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaActionPerformed(evt);
            }
        });

        cb_tinchi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel12.setText("Số tín chỉ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(bt_refresh)
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_luudiem)
                                        .addGap(83, 83, 83)
                                        .addComponent(bt_suatt))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_diemck, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_hocphan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(47, 47, 47)
                                            .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cb_tinchi, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_diemcc, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_diemgk, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(63, 63, 63)
                                .addComponent(bt_xoa))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hocphan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tinchi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diemcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diemgk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diemck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_luudiem)
                    .addComponent(bt_refresh)
                    .addComponent(bt_suatt)
                    .addComponent(bt_xoa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed
        txt_masv.setText("");
        txt_hocphan.setText("");
        txt_diemcc.setText("");
        txt_diemgk.setText("");
        txt_diemck.setText("");
    }//GEN-LAST:event_bt_refreshActionPerformed

    
    
    private void Insert() {
        if (txt_masv.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã sinh viên");
            txt_masv.requestFocus();
        }else if (txt_masv.getText().length() !=8 ) {
            JOptionPane.showMessageDialog(null, "Mã sinh viên gồm 8 số");
            txt_masv.requestFocus();
        } else if (txt_hocphan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập học phần");
            txt_hocphan.requestFocus();
        } else if (txt_diemcc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập điểm chuyên cần");
            txt_diemcc.requestFocus();
        } else if (txt_diemgk.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập điểm giữa kỳ");
            txt_diemgk.requestFocus();
        } else if (txt_diemck.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập điểm cuối kỳ");
            txt_diemck.requestFocus();
        } else {
            try {
                Connection conn = ConnectionUtils.getSQLServerConnection();
                String query = "Insert Into TB_QLDiem(Masinhvien,Hocphan,Sotinchi,Diemcc,Diemgk,Diemck,Diemthang10,Diemthang4,Diemchu) Values (?,?,?,?,?,?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(query);
                //
                int masv = Integer.parseInt(txt_masv.getText());
                String hocphan = txt_hocphan.getText();
                int sotinchi = Integer.parseInt((String) cb_tinchi.getSelectedItem());
                float diemcc = Float.parseFloat(txt_diemcc.getText());
                float diemgk = Float.parseFloat(txt_diemgk.getText());
                float diemck = Float.parseFloat(txt_diemck.getText());
                
                Points p = new Points(hoten,ngaysinh,gioitinh,quequan,masv,khoa,lop ,gmail,sdt,hocphan,sotinchi,diemcc,diemgk,diemck,diemchu); 
                ps.setString(1, txt_masv.getText());
                ps.setString(2, txt_hocphan.getText());
                ps.setString(3, (String) cb_tinchi.getSelectedItem());
                ps.setString(4, txt_diemcc.getText());
                ps.setString(5, txt_diemgk.getText());
                ps.setString(6, txt_diemck.getText());
                ps.setFloat(7, p.diemthang10());
                ps.setFloat(8, p.diemthang4());
                ps.setString(9, p.diemchu());
                ps.executeUpdate();
                Select();
                JOptionPane.showMessageDialog(null, "Đã lưu");
            } catch (SQLException | ClassNotFoundException ex) {
            }
        }
    }
    private void Select() {
        try {
            tb_ketqua2.removeAll();
            String[] arr = {"Mã sinh viên", "Học phần", "Số tín chỉ", "Điểm chuyên cần", "Điểm giữa kỳ", "Điểm cuối kỳ",
                "Thang điểm 10", "Thang điểm 4", "Điểm chữ"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            Connection conn = ConnectionUtils.getSQLServerConnection();
            String query = "Select * From TB_QLDiem";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vec = new Vector();
                vec.add(rs.getInt("Masinhvien"));
                vec.add(rs.getString("Hocphan"));
                vec.add(rs.getInt("Sotinchi"));
                vec.add(rs.getFloat("Diemcc"));
                vec.add(rs.getFloat("Diemgk"));
                vec.add(rs.getFloat("Diemck"));
                vec.add(rs.getFloat("Diemthang10"));
                vec.add(rs.getFloat("Diemthang4"));
                vec.add(rs.getString("Diemchu"));
                model.addRow(vec);
            }
            tb_ketqua2.setModel(model);
            tb_ketqua2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if(tb_ketqua2.getSelectedRow()>=0){
                        txt_masv.setText(tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 0)+"");
                        txt_hocphan.setText(tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 1)+"");
                        cb_tinchi.setSelectedItem(tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 2)+"");
                        txt_diemcc.setText(tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 3)+"");
                        txt_diemgk.setText(tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 4)+"");
                        txt_diemck.setText(tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 5)+"");
                    }
                }
            });
        } catch (ClassNotFoundException | SQLException e) {

        }
    }
    private void bt_luudiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_luudiemActionPerformed
        Insert();
    }//GEN-LAST:event_bt_luudiemActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Select();
    }//GEN-LAST:event_formComponentShown

    private void bt_suattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suattActionPerformed
        try {
            Connection conn = ConnectionUtils.getSQLServerConnection();
            String query = "UPDATE TB_QLDiem SET Sotinchi=?,Diemcc=?,Diemgk=?,Diemck=?,Diemthang10=?,Diemthang4=?,Diemchu=? WHERE Masinhvien=? AND Hocphan=?";
            PreparedStatement ps = conn.prepareStatement(query);
            int masv = Integer.parseInt(txt_masv.getText());
            String hocphan = txt_hocphan.getText();
            int sotinchi = Integer.parseInt(cb_tinchi.getSelectedItem().toString());
            float diemcc = Float.parseFloat(txt_diemcc.getText());
            float diemgk = Float.parseFloat(txt_diemgk.getText());
            float diemck = Float.parseFloat(txt_diemck.getText());
            Points p = new Points(hoten,ngaysinh,gioitinh,quequan,masv,khoa,lop ,gmail,sdt,hocphan,sotinchi,diemcc,diemgk,diemck,diemchu);
            ps.setString(8, txt_masv.getText());
            ps.setString(9, txt_hocphan.getText());
            ps.setString(1, cb_tinchi.getSelectedItem().toString());
            ps.setString(2, txt_diemcc.getText());
            ps.setString(3, txt_diemgk.getText());
            ps.setString(4, txt_diemck.getText());
            ps.setFloat(5, p.diemthang10());
            ps.setFloat(6, p.diemthang4());
            ps.setString(7, p.diemchu());
            
            ps.executeUpdate();
            Select();
            JOptionPane.showMessageDialog(null, "Sửa thành công");
        } catch (SQLException | ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_bt_suattActionPerformed

    private void bt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaActionPerformed
        try {
            Connection conn = ConnectionUtils.getSQLServerConnection();
            String query = "DELETE TB_QLDiem WHERE Masinhvien=? AND Hocphan=? AND Sotinchi=? AND Diemcc=? AND Diemgk=? AND Diemck=?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 0).toString());
            ps.setString(2, tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 1).toString());
            ps.setString(3, tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 2).toString());
            ps.setString(4, tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 3).toString());
            ps.setString(5, tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 4).toString());
            ps.setString(6, tb_ketqua2.getValueAt(tb_ketqua2.getSelectedRow(), 5).toString());
            if(JOptionPane.showConfirmDialog(this, "Xóa thông tin dòng này?","Confirm",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            ps.executeUpdate();
            Select();
            JOptionPane.showMessageDialog(null, "Xóa thành công");
        }
        } catch (SQLException | ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_bt_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_luudiem;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_suatt;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JComboBox<String> cb_tinchi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_ketqua2;
    private javax.swing.JTextField txt_diemcc;
    private javax.swing.JTextField txt_diemck;
    private javax.swing.JTextField txt_diemgk;
    private javax.swing.JTextField txt_hocphan;
    private javax.swing.JTextField txt_masv;
    // End of variables declaration//GEN-END:variables
}
