/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BigExercise;

import javax.swing.ImageIcon;

/**
 *
 * @author Orange
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbed_pane = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_qltt1 = new javax.swing.JMenuItem();
        mn_qld1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Jmenu = new javax.swing.JMenu();
        mn_timkiem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/Home-icon-16.png"))); // NOI18N
        jMenu1.setText("Hệ thống");

        mn_qltt1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mn_qltt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/Actions-document-edit-icon-16.png"))); // NOI18N
        mn_qltt1.setText("Nhập thông tin");
        mn_qltt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_qltt1ActionPerformed(evt);
            }
        });
        jMenu1.add(mn_qltt1);

        mn_qld1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mn_qld1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/Actions-document-edit-icon-16.png"))); // NOI18N
        mn_qld1.setText("Nhập điểm");
        mn_qld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_qld1ActionPerformed(evt);
            }
        });
        jMenu1.add(mn_qld1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        jMenuItem2.setText("Thoát");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        Jmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/search-icon-16.png"))); // NOI18N
        Jmenu.setText("Tìm kiếm");
        Jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuActionPerformed(evt);
            }
        });

        mn_timkiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/search-icon-16.png"))); // NOI18N
        mn_timkiem.setText("Tìm kiếm");
        mn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_timkiemActionPerformed(evt);
            }
        });
        Jmenu.add(mn_timkiem);

        jMenuBar1.add(Jmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbed_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbed_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuActionPerformed
        
    }//GEN-LAST:event_JmenuActionPerformed

    private void mn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_timkiemActionPerformed
        Timkiem tk = new Timkiem();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Icon/Icon/search-icon-16.png"));
        tabbed_pane.addTab("Tìm kiếm",icon,tk,"Tìm kiếm");
        
        tabbed_pane.setSelectedComponent(tk);
    }//GEN-LAST:event_mn_timkiemActionPerformed

    private void mn_qltt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_qltt1ActionPerformed
        Thongtinsinhvien tt = new Thongtinsinhvien();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Icon/Icon/10207-man-student-light-skin-tone-icon-16.png"));
        tabbed_pane.addTab("Quản lý thông tin sinh viên",icon,tt,"Quản lý thông tin sinh viên");
        tabbed_pane.setSelectedComponent(tt);
    }//GEN-LAST:event_mn_qltt1ActionPerformed

    private void mn_qld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_qld1ActionPerformed
        Diemsinhvien dsv = new Diemsinhvien();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Icon/Icon/10207-man-student-light-skin-tone-icon-16.png"));
        tabbed_pane.addTab("Quản lý điểm sinh viên",icon,dsv,"Quản lý điểm sinh viên");
        tabbed_pane.setSelectedComponent(dsv);
    }//GEN-LAST:event_mn_qld1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Gioithieu nj = new Gioithieu();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Icon/Icon/10207-man-student-light-skin-tone-icon-16.png"));
        tabbed_pane.addTab("Giới thiệu",icon,nj,"Giới thiệu");
        tabbed_pane.setSelectedComponent(nj);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Jmenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mn_qld1;
    private javax.swing.JMenuItem mn_qltt1;
    private javax.swing.JMenuItem mn_timkiem;
    private javax.swing.JTabbedPane tabbed_pane;
    // End of variables declaration//GEN-END:variables
}
