/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BigExercise;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Orange
 */
public class Thongtinsinhvien extends javax.swing.JPanel {

    /**
     * Creates new form Thongtinsinhvien
     */
    public Thongtinsinhvien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_refresh = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cb_quequan = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txt_gmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ketqua1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        txt_masv = new javax.swing.JTextField();
        cb_lop = new javax.swing.JComboBox<>();
        cb_khoa = new javax.swing.JComboBox<>();
        txt_sdt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_ngaysinh = new javax.swing.JTextField();
        bt_luuthongtin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cb_gioitinh = new javax.swing.JComboBox<>();
        bt_suatt = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        bt_refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/new-icon-16.png"))); // NOI18N
        bt_refresh.setText("Làm mới");
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel12.setText("Quê quán");

        cb_quequan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Bà rịa – Vũng tàu", "Bắc Giang", "Bắc Kạn", "Bạc Liêu", "Bắc Ninh", "Bến Tre", "Bình Định", "Bình Dương", "Bình Phước", "Bình Thuận", "Cà Mau", "Cần Thơ", "Cao Bằng", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội ", "Hà Tĩnh", "Hải Dương", "Hải Phòng", "Hậu Giang", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lâm Đồng", "Lạng Sơn", "Lào Cai", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế", "Tiền Giang", "Thành phố Hồ Chí Minh", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái" }));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel13.setText("Gmail");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("Ngày sinh");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("Mã sinh viên");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/logo-1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("Lớp");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("Khoa");

        tb_ketqua1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Họ và tên", "Ngày sinh", "Giới tính", "Quê quán", "Gmail", "Số điện thoại", "Khoa", "Lớp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_ketqua1);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("Số điện thoại");

        cb_lop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC.CNTT11.10", "DC.OT11.10", "DC.DDT11.10", "DC.TDH11.10", "DC.CNTP11.10", "DC.CNCTM11.10", "DC.NDL11.10", " ", " ", " ", " " }));

        cb_khoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công nghệ thông tin", "Công nghệ kỹ thuật điện – điện tử", "Công nghệ kỹ thuật nhiệt (điện lạnh)", "Công nghệ Kỹ thuật điều khiển – tự động hóa", "Công nghệ thực phẩm", "Công nghệ chế tạo máy", "Công nghệ kỹ thuật ô tô" }));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("Họ và tên");

        txt_ngaysinh.setForeground(new java.awt.Color(102, 102, 102));
        txt_ngaysinh.setText("dd/mm/yyyy");
        txt_ngaysinh.setToolTipText("");
        txt_ngaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ngaysinhActionPerformed(evt);
            }
        });

        bt_luuthongtin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_luuthongtin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/Save-icon.png"))); // NOI18N
        bt_luuthongtin.setText("Lưu thông tin");
        bt_luuthongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_luuthongtinActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel8.setText("Giới tính");

        cb_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        bt_suatt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_suatt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/Actions-document-edit-icon-16.png"))); // NOI18N
        bt_suatt.setText("Sửa thông tin");
        bt_suatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suattActionPerformed(evt);
            }
        });

        bt_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        bt_xoa.setText("Xóa thông tin");
        bt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(bt_refresh)
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_quequan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_gmail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_luuthongtin)
                                .addGap(83, 83, 83)
                                .addComponent(bt_suatt)
                                .addGap(70, 70, 70)
                                .addComponent(bt_xoa))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_quequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_gmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_luuthongtin)
                    .addComponent(bt_refresh)
                    .addComponent(bt_suatt)
                    .addComponent(bt_xoa))
                .addGap(142, 142, 142))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(431, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed
        // TODO add your handling code here:
        txt_masv.setText("");
        txt_hoten.setText("");
        txt_ngaysinh.setText("");
        cb_khoa.setSelectedItem("");
        cb_lop.setSelectedItem("");
        txt_gmail.setText("");
        txt_sdt.setText("");
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void txt_ngaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ngaysinhActionPerformed
    private boolean checkGmail() {
        try {
            Connection conn = ConnectionUtils.getSQLServerConnection();
            String query = "Select * From TB_QLThongtin Where Gmail=?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, txt_gmail.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return true;
            }
        } catch (ClassNotFoundException | SQLException e) {

        }
        return false;
    }
    private boolean checkSdt() {
        try {
            Connection conn = ConnectionUtils.getSQLServerConnection();
            String query = "Select * From TB_QLThongtin Where Sodienthoai=?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, txt_sdt.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return true;
            }
        } catch (ClassNotFoundException | SQLException e) {

        }
        return false;
    }
    private boolean checkMasinhvien() {
        try {
            Connection conn = ConnectionUtils.getSQLServerConnection();
            String query = "Select * From TB_QLThongtin Where Masinhvien=?";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, txt_masv.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return true;
            }
        } catch (ClassNotFoundException | SQLException e) {

        }
        return false;
    }
    private void Insert() {
        if (txt_hoten.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập họ tên");
            txt_hoten.requestFocus();
        } else if (txt_ngaysinh.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập ngày sinh");
            txt_ngaysinh.requestFocus();
        } else if (txt_masv.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã sinh viên");
            txt_masv.requestFocus();
        }else if (txt_masv.getText().length() !=8 ) {
            JOptionPane.showMessageDialog(null, "Mã sinh viên gồm 8 số");
            txt_masv.requestFocus();
        } else if (checkMasinhvien() == true) {
            JOptionPane.showMessageDialog(null, "Mã sinh viên đã tồn tại");
            txt_masv.requestFocus();
        }else if (txt_gmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập địa chỉ gmail");
            txt_gmail.requestFocus();
        }else if (checkGmail() == true) {
            JOptionPane.showMessageDialog(null, "Gmail đã tồn tại");
            txt_gmail.requestFocus();
        }else if (txt_gmail.getText().matches("^[a-z][a-z0-9_\\.]{5,32}@[a-z0-9]{2,}(\\.[a-z0-9]{2,4}){1,2}$") == false) {
            JOptionPane.showMessageDialog(null, "Gmail gồm 5-32 kí tự @gmail.com");
            txt_gmail.requestFocus();
        } else if (txt_sdt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập số điện thoại");
            txt_sdt.requestFocus();
        } else if (txt_sdt.getText().matches("(\\+84|0)\\d{9,10}") == false) {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ");
            txt_sdt.requestFocus();
        } else if (checkSdt() == true) {
            JOptionPane.showMessageDialog(null, "Số điện thoại đã tồn tại");
            txt_sdt.requestFocus();
        } else {
            try {
                Connection conn = ConnectionUtils.getSQLServerConnection();
                String query = "Insert Into TB_QLThongtin(Masinhvien,Hovaten,Ngaysinh,Gioitinh,Quequan,Gmail,Sodienthoai,Khoa,Lop) Values(?,?,?,?,?,?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(query);
                //
                ps.setString(1, txt_masv.getText());
                ps.setString(2, txt_hoten.getText());
                ps.setString(3, txt_ngaysinh.getText());
                ps.setString(4, (String) cb_gioitinh.getSelectedItem());
                ps.setString(5, (String) cb_quequan.getSelectedItem());
                ps.setString(6, txt_gmail.getText());
                ps.setString(7, txt_sdt.getText());
                ps.setString(8, (String) cb_khoa.getSelectedItem());
                ps.setString(9, (String) cb_lop.getSelectedItem());
                ps.executeUpdate();
                Select();
                JOptionPane.showMessageDialog(null, "Đã lưu");
            } catch (SQLException | ClassNotFoundException ex) {
            }
        }
    }
    private void Select() {
        try {
            tb_ketqua1.removeAll();
            String[] arr = {"Mã sinh viên","Họ và tên", "Ngày sinh", "Giới tính", "Quê quán",
                "Gmail", "SĐT", "Khoa", "Lớp"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            Connection conn = ConnectionUtils.getSQLServerConnection();
            String query = "Select * From TB_QLThongtin";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vec = new Vector();
                vec.add(rs.getInt("Masinhvien"));
                vec.add(rs.getString("Hovaten"));
                vec.add(rs.getString("Ngaysinh"));
                vec.add(rs.getString("Gioitinh"));
                vec.add(rs.getString("Quequan"));
                vec.add(rs.getString("Gmail"));
                vec.add(rs.getString("Sodienthoai"));
                vec.add(rs.getString("Khoa"));
                vec.add(rs.getString("Lop"));
                model.addRow(vec);
            }
            tb_ketqua1.setModel(model);
            tb_ketqua1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if(tb_ketqua1.getSelectedRow()>=0){
                        txt_masv.setText(tb_ketqua1.getValueAt(tb_ketqua1.getSelectedRow(), 0)+"");
                        txt_hoten.setText(tb_ketqua1.getValueAt(tb_ketqua1.getSelectedRow(), 1)+"");
                        txt_ngaysinh.setText(tb_ketqua1.getValueAt(tb_ketqua1.getSelectedRow(), 2)+"");
                        cb_gioitinh.setSelectedItem(tb_ketqua1.getModel().getValueAt(tb_ketqua1.getSelectedRow(), 3)+"");
                        cb_quequan.setSelectedItem(tb_ketqua1.getModel().getValueAt(tb_ketqua1.getSelectedRow(), 4)+"");
                        txt_gmail.setText(tb_ketqua1.getValueAt(tb_ketqua1.getSelectedRow(), 5)+"");
                        txt_sdt.setText(tb_ketqua1.getValueAt(tb_ketqua1.getSelectedRow(), 6)+"");
                        cb_khoa.setSelectedItem(tb_ketqua1.getModel().getValueAt(tb_ketqua1.getSelectedRow(), 7)+"");
                        cb_lop.setSelectedItem(tb_ketqua1.getModel().getValueAt(tb_ketqua1.getSelectedRow(), 8)+"");
                    }
                }
            });
        } catch (ClassNotFoundException | SQLException e) {

        }
    }
    private void bt_luuthongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_luuthongtinActionPerformed
        Insert();
    }//GEN-LAST:event_bt_luuthongtinActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Select();
    }//GEN-LAST:event_formComponentShown

    private void bt_suattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suattActionPerformed
        try {
                Connection conn = ConnectionUtils.getSQLServerConnection();
                String query = "UPDATE TB_QLThongtin SET Hovaten=?,Ngaysinh=?,Gioitinh=?,Quequan=?,Gmail=?,Sodienthoai=?,Khoa=?,Lop=? WHERE Masinhvien=?";
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(9, txt_masv.getText());
                ps.setString(1, txt_hoten.getText());
                ps.setString(2, txt_ngaysinh.getText());
                ps.setString(3, cb_gioitinh.getSelectedItem().toString());
                ps.setString(4, cb_quequan.getSelectedItem().toString());
                ps.setString(5, txt_gmail.getText());
                ps.setString(6, txt_sdt.getText());
                ps.setString(7, cb_khoa.getSelectedItem().toString());
                ps.setString(8, cb_lop.getSelectedItem().toString());
                ps.executeUpdate();
                Select();
                JOptionPane.showMessageDialog(null, "Sửa thành công");
            } catch (SQLException | ClassNotFoundException ex) {
            }
    }//GEN-LAST:event_bt_suattActionPerformed

    private void bt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaActionPerformed
        try {
                Connection conn = ConnectionUtils.getSQLServerConnection();
                String query = "DELETE TB_QLThongtin WHERE Masinhvien=?";
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(1, tb_ketqua1.getValueAt(tb_ketqua1.getSelectedRow(), 0).toString());
                if(JOptionPane.showConfirmDialog(this, "Xóa thông tin dòng này?","Confirm",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                    ps.executeUpdate();
                    Select();
                    JOptionPane.showMessageDialog(null, "Xóa thành công");
                }
            } catch (SQLException | ClassNotFoundException ex) {
            }
    }//GEN-LAST:event_bt_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_luuthongtin;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_suatt;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JComboBox<String> cb_gioitinh;
    private javax.swing.JComboBox<String> cb_khoa;
    private javax.swing.JComboBox<String> cb_lop;
    private javax.swing.JComboBox<String> cb_quequan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_ketqua1;
    private javax.swing.JTextField txt_gmail;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_masv;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_sdt;
    // End of variables declaration//GEN-END:variables
}
